"""add extracted text to interview documents

Revision ID: e3bf5523a3ea
Revises: f95bc22620ce
Create Date: 2026-08-15 11:31:43.725901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bf5523a3ea'
down_revision: Union[str, Sequence[str], None] = 'f95bc22620ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_documents', 'extracted_text')
    # ### end Alembic commands ###
