"""add unique constraint to interview responses

Revision ID: f95bc22620ce
Revises: 9411159bdb79
Create Date: 2026-08-05 20:06:46.038083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95bc22620ce'
down_revision: Union[str, Sequence[str], None] = '9411159bdb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_interview_response_question', 'interview_responses', ['interview_session_id', 'question_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interview_response_question', 'interview_responses', type_='unique')
    # ### end Alembic commands ###
